# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstagramClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'SDWebImage', '~> 5.0'

  # Pods for InstagramClone

end
